// Go schema for src/specs/items/index.ts. Values are generated by generate-go-catalog.ts.
package specs

type Item struct {
	Rounds    int       `json:"rounds"`
	Resource  int       `json:"resource"`
	Name      string    `json:"name"`
	Price     *float64  `json:"price"`
	Points    []Point   `json:"points"`
	Radius    float64   `json:"radius"`
	Lines     [][]Point `json:"lines"`
	Shades    []string  `json:"shades"`
	Glint     bool      `json:"glint"`
	Rainbow   bool      `json:"rainbow"`
	FillAlpha float64   `json:"fillAlpha"`
	Unlock    string    `json:"unlock"`
}
