// Go schema for src/specs/modules/index.ts. Values are generated by generate-go-catalog.ts.
package specs

type ModelPart struct {
	Color  *float64 `json:"color"`
	Points []Point  `json:"points"`
}

type Projectile struct {
	Speed     float64 `json:"speed"`
	Lifetime  float64 `json:"lifetime"`
	Radius    float64 `json:"radius"`
	Color     string  `json:"color"`
	Explosion *struct {
		Radius   float64 `json:"radius"`
		Impulse  float64 `json:"impulse"`
		MaxSpeed float64 `json:"maxSpeed"`
		Damage   float64 `json:"damage"`
	} `json:"explosion"`
	Glow *struct {
		Color  string  `json:"color"`
		Alpha  float64 `json:"alpha"`
		Radius float64 `json:"radius"`
	} `json:"glow"`
}

type Module struct {
	FireInterval                       float64     `json:"fireInterval"`
	Recoil                             float64     `json:"recoil"`
	Projectile                         Projectile  `json:"projectile"`
	Ammunition                         *int        `json:"ammunition"`
	BarrelLength                       float64     `json:"barrelLength"`
	Model                              []ModelPart `json:"model"`
	Behavior                           string      `json:"behavior"`
	Name                               string      `json:"name"`
	Health, Price                      float64
	ZIndex                             int       `json:"zIndex"`
	Shades                             []string  `json:"shades"`
	ActivationDuration                 float64   `json:"activationDuration"`
	ActivationThreshold                float64   `json:"activationThreshold"`
	Bounciness                         *float64  `json:"bounciness"`
	Friction                           *float64  `json:"friction"`
	Damage                             float64   `json:"damage"`
	DamageStepsPerSecond               float64   `json:"damageStepsPerSecond"`
	GripDecay                          float64   `json:"gripDecay"`
	GripScale                          float64   `json:"gripScale"`
	DisablePhysics                     bool      `json:"disablePhysics"`
	ForwardThrust                      float64   `json:"forwardThrust"`
	RotationalThrust                   float64   `json:"rotationalThrust"`
	Offset                             float64   `json:"offset"`
	FlareSizes                         []float64 `json:"flareSizes"`
	NozzleSides                        []float64 `json:"nozzleSides"`
	CollectsCargo                      bool      `json:"collectsCargo"`
	Grinds                             bool      `json:"grinds"`
	Beam                               bool      `json:"beam"`
	Lens, Mouth, Reach, Spread, Corner float64
	ShieldRadius                       float64  `json:"shieldRadius"`
	CoverDuration                      float64  `json:"coverDuration"`
	GeneratorRadius                    float64  `json:"generatorRadius"`
	UnhurtWhen                         *float64 `json:"unhurtWhen"`
	DrillTip                           struct {
		Position Vector  `json:"position"`
		Radius   float64 `json:"radius"`
	} `json:"drillTip"`
	Points        []Point `json:"points"`
	CargoGeometry struct {
		Length           float64 `json:"length"`
		OpenAngle        float64 `json:"openAngle"`
		DoorWidth        float64 `json:"doorWidth"`
		DoorRadius       float64 `json:"doorRadius"`
		OpeningThreshold float64 `json:"openingThreshold"`
		ThroatRadius     float64 `json:"throatRadius"`
	} `json:"cargoGeometry"`
}
