// Go schema for src/specs/ships/index.ts. Values are generated by generate-go-catalog.ts.
package specs

type MountPoint struct {
	ThrusterOffset float64  `json:"thrusterOffset"`
	X              float64  `json:"x"`
	Y              float64  `json:"y"`
	Fits           []string `json:"fits"`
}

type HullSegment struct {
	DisablePhysics bool           `json:"disablePhysics"`
	DockSegment    bool           `json:"dockSegment"`
	Shades         []string       `json:"shades"`
	ZIndex         *int           `json:"zIndex"`
	Health         *float64       `json:"health"`
	Points         []Point        `json:"points"`
	Core           bool           `json:"core"`
	Mounts         [][]MountPoint `json:"mounts"`
}

type InitialModule struct {
	Mount  int    `json:"mount"`
	Module string `json:"module"`
}

type Ship struct {
	InitialLoadout []InitialModule `json:"initialLoadout"`
	Name           string          `json:"name"`
	CargoSpace     int             `json:"cargoSpace"`
	Drag           float64         `json:"drag"`
	Mass           float64         `json:"mass"`
	Radius         float64         `json:"radius"`
	TurnRate       float64         `json:"turnRate"`
	HullSegments   []HullSegment   `json:"hullSegments"`
}
