import { colors } from '../colors';

export const plasmaExplosion = [
  {
    alpha: 0.75,
    color: colors.violet[2],
    delay: 32,
    duration: 310,
    easeOut: 310 / 130,
    fadeDuration: 230,
    radius: 52,
    scale: [0.4, 1],
    type: 'glow',
  },
  {
    color: colors.violet[2],
    delay: 32,
    duration: 270,
    easeOut: 270 / 110,
    endLineWidth: 0,
    fadeDuration: 270,
    lineWidth: 2.5,
    radius: 36,
    scale: [0.04, 1],
    type: 'ring',
  },
  {
    color: colors.violet[2],
    duration: 32,
    easeOut: 2,
    pointCount: 7,
    radius: 16,
    radiusEven: 4,
    scale: [0.4, 1],
    type: 'polygon',
  },
  {
    color: colors.violet[2],
    delay: 32,
    dissolveDuration: 190,
    duration: 210,
    easeOut: 210 / 90,
    fadeDuration: 80,
    pointCount: 7,
    radius: 26,
    radiusEven: [6.5, 19.5],
    scale: [0.15, 1],
    type: 'polygon',
  },
  {
    color: colors.violet[2],
    delay: 32,
    duration: 70,
    easeOut: 2,
    fadeDuration: 20,
    pointCount: 7,
    radius: 16,
    radiusEven: [4, 12],
    scale: [1, 0],
    type: 'polygon',
  },
] as const;
