import { colors } from '../colors';

export const plasmaExplosion = [
  {
    alpha: 0.75,
    color: colors.violet[2],
    delay: 32,
    duration: 310,
    easeOut: 310 / 130,
    fadeDuration: 230,
    radius: 52,
    scale: [0.4, 1],
    type: 'glow',
  },
  {
    color: colors.violet[2],
    delay: 64,
    duration: 405,
    easeOut: 270 / 110,
    endLineWidth: 0,
    fadeDuration: 405,
    lineWidth: 2,
    radius: 10,
    scale: [0, 3.5],
    type: 'ring',
  },
  {
    color: colors.black[0],
    duration: 16,
    easeOut: 2,
    pointCount: 7,
    radius: 16,
    radiusEven: 4,
    scale: [0.4, 1],
    type: 'polygon',
  },
  {
    color: colors.white[2],
    delay: 16,
    duration: 16,
    pointCount: 7,
    radius: 16,
    radiusEven: 4,
    type: 'polygon',
  },
  {
    color: colors.violet[2],
    delay: 32,
    dissolveDuration: 190,
    duration: 210,
    easeOut: 210 / 90,
    fadeDuration: 80,
    pointCount: 7,
    radius: 26,
    radiusEven: [6.5, 19.5],
    scale: [0.15, 1],
    type: 'polygon',
  },
  {
    color: colors.violet[2],
    delay: 32,
    duration: 70,
    easeOut: 2,
    fadeDuration: 20,
    pointCount: 7,
    radius: 16,
    radiusEven: [4, 12],
    scale: [1, 0],
    type: 'polygon',
  },
] as const;
