// Go schema for src/definitions/simulation.ts. Values are generated by generate-go-catalog.ts.
package definitions

type UpdateTier struct{ Substeps, UpdateEvery, ReplicateEvery int }
type Motion struct {
	DefaultDrag         float64 `json:"defaultDrag"`
	DefaultMaxSpeed     float64 `json:"defaultMaxSpeed"`
	MaxSpeedDrag        float64 `json:"maxSpeedDrag"`
	MinimumSpeedSquared float64 `json:"minimumSpeedSquared"`
}
type Flight struct {
	ThrustScale         float64 `json:"thrustScale"`
	SteeringEase        float64 `json:"steeringEase"`
	SpinDivisor         float64 `json:"spinDivisor"`
	LaunchDuration      float64 `json:"launchDuration"`
	LaunchHalfThreshold float64 `json:"launchHalfThreshold"`
	LaunchHalfEnd       float64 `json:"launchHalfEnd"`
	LaunchThrottle      float64 `json:"launchThrottle"`
	SpeedPerThrust      float64 `json:"speedPerThrust"`
	UncrewedMaxSpeed    float64 `json:"uncrewedMaxSpeed"`
	AngularInertiaScale float64 `json:"angularInertiaScale"`
}
type Replication struct {
	EntityLoad   float64 `json:"entityLoad"`
	EntityUnload float64 `json:"entityUnload"`
	MarkerLoad   float64 `json:"markerLoad"`
	MarkerUnload float64 `json:"markerUnload"`
}
type Physics struct {
	MaxTranslation      float64 `json:"maxTranslation"`
	MaxRotation         float64 `json:"maxRotation"`
	VelocityIterations  int     `json:"velocityIterations"`
	PositionIterations  int     `json:"positionIterations"`
	WakeMargin          float64 `json:"wakeMargin"`
	AabbExtension       float64 `json:"aabbExtension"`
	AabbMultiplier      float64 `json:"aabbMultiplier"`
	PositionBaumgarte   float64 `json:"positionBaumgarte"`
	TOIBaumgarte        float64 `json:"toiBaumgarte"`
	MaxLinearCorrection float64 `json:"maxLinearCorrection"`
	DamageBase          float64 `json:"damageBase"`
	DamageScale         float64 `json:"damageScale"`
}
type Simulation struct {
	LinearSlop              float64               `json:"linearSlop"`
	ContactSpeedThreshold   float64               `json:"contactSpeedThreshold"`
	Physics                 Physics               `json:"physics"`
	SimulationStep          float64               `json:"simulationStep"`
	MaxCatchUpTicks         int                   `json:"maxCatchUpTicks"`
	MaxPredictionTicks      int                   `json:"maxPredictionTicks"`
	VisibleRange            float64               `json:"visibleRange"`
	BallisticReplicateEvery int                   `json:"ballisticReplicateEvery"`
	RegionSize              float64               `json:"regionSize"`
	PreGeneratedRadius      float64               `json:"preGeneratedRadius"`
	UpdateTiers             map[string]UpdateTier `json:"updateTiers"`
	WorldRanges             map[string]float64    `json:"worldRanges"`
	ServerRegionRanges      map[string]float64    `json:"serverRegionRanges"`
	Replication             Replication           `json:"replication"`
	Motion                  Motion                `json:"motion"`
	Flight                  Flight                `json:"flight"`
}
