import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { colors, paintColors } from '../src/shared/colors';
import {
  itemDefaults,
  itemIds,
  itemSpecifications,
} from '../src/shared/specification/items';
import {
  moduleIds,
  moduleSpecifications,
} from '../src/shared/specification/modules';
import { shipSpecifications } from '../src/shared/specification/ships';
import { stationSpecifications } from '../src/shared/specification/stations';
import {
  binaryFieldIds,
  controlMessageIds,
  dockActionIds,
  entityKindIds,
} from '../src/shared/specification/protocol';
import { simulationSpecification } from '../src/shared/specification/simulation';
import { regionGenerationSpecification } from '../src/shared/specification/regions';

const catalog = {
  colors,
  paintColors,
  itemDefaults,
  itemIds,
  itemSpecifications,
  moduleIds,
  moduleSpecifications,
  shipSpecifications,
  stationSpecifications,
  protocol: { binaryFieldIds, controlMessageIds, dockActionIds, entityKindIds },
  simulation: simulationSpecification,
  regionGeneration: regionGenerationSpecification,
};
const unique = (values: readonly (number | string)[]) =>
  new Set(values).size === values.length;

if (
  !unique(moduleIds) ||
  !unique(itemIds) ||
  !itemIds.every((id, index) => itemSpecifications[id].resource === index) ||
  !moduleIds.every((id) => id in moduleSpecifications) ||
  !shipSpecifications.mustang.startingModules.every(
    (id) => id in moduleSpecifications,
  ) ||
  !shipSpecifications.mustang.hullSegments.every(
    (segment) =>
      !('mounts' in segment) ||
      segment.mounts?.every((mount) =>
        mount.fits.every((id) => id in moduleSpecifications),
      ),
  ) ||
  !unique(Object.values(binaryFieldIds)) ||
  Object.values(binaryFieldIds).some((value, index) => value !== index + 1) ||
  !unique(Object.values(controlMessageIds)) ||
  !unique(Object.values(dockActionIds)) ||
  !unique(Object.values(entityKindIds))
) {
  throw new Error('Invalid shared specification IDs');
}

const json = JSON.stringify(catalog);
const digest = createHash('sha256').update(json).digest('hex');
const physics = simulationSpecification.physics;
const numericConstants = {
  LinearSlop: simulationSpecification.linearSlop,
  ContactSpeedThreshold: simulationSpecification.contactSpeedThreshold,
  AabbExtension: physics.aabbExtension,
  AabbMultiplier: physics.aabbMultiplier,
  MaxTranslation: physics.maxTranslation,
  MaxRotation: physics.maxRotation,
  MaxLinearCorrection: physics.maxLinearCorrection,
  PositionBaumgarte: physics.positionBaumgarte,
  ToiBaumgarte: physics.toiBaumgarte,
};
const constants = Object.entries(numericConstants)
  .map(([name, value]) => `const ${name} = ${value}`)
  .join('\n');
const source = `// Code generated by scripts/generate-go-catalog.ts; DO NOT EDIT.\n// SHA-256: ${digest}\npackage specification\n\nconst catalogJSON = ${JSON.stringify(json)}\n\n${constants}\n`;

writeFileSync('internal/specification/catalog_gen.go', source);
