// Go schema for src/shared/specification/items.ts. Values are generated by generate-go-catalog.ts.
package specification

type Item struct {
	Resource  int       `json:"resource"`
	Label     string    `json:"label"`
	Price     *float64  `json:"price"`
	Points    []Point   `json:"points"`
	Radius    float64   `json:"radius"`
	Lines     [][]Point `json:"lines"`
	Shades    []string  `json:"shades"`
	Glint     bool      `json:"glint"`
	Rainbow   bool      `json:"rainbow"`
	FillAlpha float64   `json:"fillAlpha"`
	Unlock    string    `json:"unlock"`
}
