// Go schema for src/shared/specification/protocol.ts. Values are generated by generate-go-catalog.ts.
package specification

type Protocol struct {
	BinaryFieldIDs    map[string]int `json:"binaryFieldIds"`
	ControlMessageIDs map[string]int `json:"controlMessageIds"`
	DockActionIDs     map[string]int `json:"dockActionIds"`
	EntityKindIDs     map[string]int `json:"entityKindIds"`
}
