// Go schema for src/shared/specification/regions.ts. Values are generated by generate-go-catalog.ts.
package specification

type FeatureSpecification struct {
	Size      float64 `json:"size"`
	Chance    float64 `json:"chance"`
	Clearance float64 `json:"clearance"`
	Kind      uint32  `json:"kind"`
}
type RegionGeneration struct {
	Features                 []FeatureSpecification `json:"features"`
	StationStream            uint32                 `json:"stationStream"`
	StationRadius            float64                `json:"stationRadius"`
	WreckRadius              float64                `json:"wreckRadius"`
	FieldRadius              float64                `json:"fieldRadius"`
	FieldRadiusRange         float64                `json:"fieldRadiusRange"`
	RichFieldAmethystChance  float64                `json:"richFieldAmethystChance"`
	RichFieldGoldChance      float64                `json:"richFieldGoldChance"`
	NearestFieldInitialRange float64                `json:"nearestFieldInitialRange"`
	FieldSearchMargin        float64                `json:"fieldSearchMargin"`
	AsteroidCounts           map[string]int         `json:"asteroidCounts"`
	AsteroidBaseRadius       float64                `json:"asteroidBaseRadius"`
	AsteroidAmethystRadius   float64                `json:"asteroidAmethystRadius"`
	AsteroidAmethystRange    float64                `json:"asteroidAmethystRange"`
	AsteroidGoldRadius       float64                `json:"asteroidGoldRadius"`
	AsteroidGoldRange        float64                `json:"asteroidGoldRange"`
	AsteroidMixedRadius      float64                `json:"asteroidMixedRadius"`
	AsteroidMixedRange       float64                `json:"asteroidMixedRange"`
	MixedItemChance          float64                `json:"mixedItemChance"`
	MixedItemLimit           int                    `json:"mixedItemLimit"`
	AsteroidSpacing          float64                `json:"asteroidSpacing"`
	AsteroidVariance         float64                `json:"asteroidVariance"`
	AsteroidPointCountScale  float64                `json:"asteroidPointCountScale"`
}
