// Go schema for src/shared/specification/ships.ts. Values are generated by generate-go-catalog.ts.
package specification

type Mount struct {
	Fits          []string `json:"fits"`
	LocalPosition Vector   `json:"localPosition"`
}
type HullSegment struct {
	Health float64 `json:"health"`
	Points []Point `json:"points"`
	Core   bool    `json:"core"`
	Mounts []Mount `json:"mounts"`
}
type Ship struct {
	CargoSpace      int           `json:"cargoSpace"`
	Drag            float64       `json:"drag"`
	Mass            float64       `json:"mass"`
	Radius          float64       `json:"radius"`
	TurnRate        float64       `json:"turnRate"`
	HullSegments    []HullSegment `json:"hullSegments"`
	StartingModules []string      `json:"startingModules"`
	StartingCredits float64       `json:"startingCredits"`
}
