// Go schema for src/shared/specification/stations.ts. Values are generated by generate-go-catalog.ts.
package specification

type StationGeometry struct {
	Bay struct {
		Back   float64 `json:"back"`
		Corner float64 `json:"corner"`
		Lip    float64 `json:"lip"`
		Nose   float64 `json:"nose"`
		Seam   float64 `json:"seam"`
	} `json:"bay"`
	Core   []Point   `json:"core"`
	Panels [][]Point `json:"panels"`
	Sides  []struct {
		Opening      bool    `json:"opening"`
		ShapeOutline []Point `json:"shapeOutline"`
	} `json:"sides"`
}
type Station struct {
	LocalMovementRadius float64         `json:"localMovementRadius"`
	Mass                float64         `json:"mass"`
	ZIndex              float64         `json:"zIndex"`
	BayFillAlpha        float64         `json:"bayFillAlpha"`
	BayFloorZIndex      float64         `json:"bayFloorZIndex"`
	BayCeilingZIndex    float64         `json:"bayCeilingZIndex"`
	BayGlowShades       []string        `json:"bayGlowShades"`
	Geometry            StationGeometry `json:"geometry"`
}
