// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 179);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1788707521);
user_pref("browser.search.region", "GB");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":26,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "182a38d2-eb9a-46e3-bb29-ddbdfd9a1387");
user_pref("datareporting.dau.cachedUsageProfileID", "2a5118ab-66cd-4b66-9768-63710e7b37fe");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "155.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260904071051");
user_pref("extensions.lastAppVersion", "155.0.1");
user_pref("extensions.lastPlatformVersion", "155.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5338b452-240e-43d2-a4cd-9b44a041eb63\",\"ipp-activator@mozilla.com\":\"e21f78fd-6d8c-44c4-9f87-7f993821806a\",\"pictureinpicture@mozilla.org\":\"d95f5dd3-b516-40b0-8b72-b642e17026b9\",\"addons-search-detection@mozilla.com\":\"57b7db1a-9566-47d8-8c03-0aee9d28a14b\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"d9a1055c-a7f2-4ed1-b0e6-354fc21486c4\",\"default-theme@mozilla.org\":\"9194a14e-b993-4b3d-a6e7-2810fcc78208\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "24fdfa41-15cc-4a88-a90b-c8576d5497f5");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("services.settings.base_attachments_url", "https://firefox.settings.services.mozilla.com/v2|https://firefox-settings-attachments.cdn.mozilla.net/");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.startup.last_success", 1788707520);
user_pref("toolkit.telemetry.cachedClientID", "c58fee14-a99e-4bfe-9b5c-54a4b43c4eab");
user_pref("toolkit.telemetry.cachedProfileGroupID", "061e1a72-5aa3-4663-883f-05facfde172b");
user_pref("toolkit.telemetry.previousBuildID", "20260904071051");
